sudo: required
services:
  - docker
before_install:
  - docker build -t arukulka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run arukulka/react-test npm test -- --coverage

after_success:
  - docker build -t arukulka/multi-client ./client
  - docker build -t arukulka/multi-nginx ./nginx
  - docker build -t arukulka/multi-server ./server
  - docker build -t arukulka/multi-worker ./worker
# login to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


# taken the images to Docker Hub
  - docker push arukulka/multi-client
  - docker push arukulka/multi-nginx
  - docker push arukulka/multi-server
  - docker push arukulka/multi-worker


 
